# Generated by Django 4.2.9 on 2024-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=30)),
                ('monster_type', models.CharField(max_length=30)),
                ('health_points', models.IntegerField(default=0)),
            ],
        ),
    ]
