# Generated by Django 4.2.9 on 2024-03-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonmonster',
            name='monster_sprite',
            field=models.ImageField(default='pollution/test_monster1', upload_to='pollution/'),
        ),
    ]
