# Generated by Django 5.0.2 on 2024-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0004_carbonmonsterrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonmonster',
            name='monster_sprite',
            field=models.ImageField(default='pollution/monster1.png', upload_to='pollution/'),
        ),
    ]
