# Generated by Django 5.0.1 on 2024-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(default='Location', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(default='Answer', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
