# Generated by Django 5.0.1 on 2024-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_location_alter_task_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Code', max_length=30)),
                ('name', models.CharField(default='Name', max_length=30)),
                ('location', models.CharField(default='Location', max_length=30)),
                ('description', models.CharField(default='description', max_length=200)),
                ('question', models.CharField(default='Question', max_length=300)),
                ('choices', models.CharField(default='Choices', max_length=30)),
                ('correct_answer', models.CharField(default='Answer', max_length=300)),
            ],
        ),
    ]
