# Generated by Django 5.0.1 on 2024-02-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_multiplechoicetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicetask',
            name='choices',
        ),
        migrations.AddField(
            model_name='multiplechoicetask',
            name='choice1',
            field=models.CharField(default='Choice1', max_length=30),
        ),
        migrations.AddField(
            model_name='multiplechoicetask',
            name='choice2',
            field=models.CharField(default='Choice2', max_length=30),
        ),
        migrations.AddField(
            model_name='multiplechoicetask',
            name='choice3',
            field=models.CharField(default='Choice3', max_length=30),
        ),
        migrations.AddField(
            model_name='multiplechoicetask',
            name='choice4',
            field=models.CharField(default='Choice4', max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='description',
            field=models.CharField(default='Description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Description', max_length=200),
        ),
    ]
