# Generated by Django 5.0.1 on 2024-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_multiplechoicetask_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='description',
            field=models.CharField(blank=True, default='Description', max_length=200, null=True),
        ),
    ]
