# Generated by Django 5.0.1 on 2024-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_multiplechoicetask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='choice1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='choice2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='choice3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='choice4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='correct_answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
