# Generated by Django 5.0.1 on 2024-02-26 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_multiplechoicetask_choice1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='correct_answer',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
