# Generated by Django 5.0.1 on 2024-02-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_usercoderelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbasedcode',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
