# Generated by Django 5.0.1 on 2024-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_personbasedcode_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBasedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
