# Generated by Django 5.0.1 on 2024-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_userlocationrelation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonBasedCode',
            new_name='PersonBasedCodeChallenge',
        ),
        migrations.AlterField(
            model_name='multiplechoicetask',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
