# Generated by Django 5.0.1 on 2024-02-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_rename_personbasedcode_personbasedcodechallenge_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoiceTask',
            new_name='MultipleChoiceChallenge',
        ),
    ]
