# Generated by Django 5.0.1 on 2024-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_rename_multiplechoicetask_multiplechoicechallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicechallenge',
            name='description',
            field=models.TextField(blank=True, default='This is a multiple choice task', max_length=200),
        ),
    ]
