# Generated by Django 5.0.1 on 2024-02-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_multiplechoicechallenge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicechallenge',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
