# Generated by Django 5.0.1 on 2024-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_usermcqrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicechallenge',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='multiplechoicechallenge',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
