# Generated by Django 5.0.2 on 2024-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_points'),
        ('tasks', '0002_task_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to='tasks.task'),
        ),
    ]
