# Generated by Django 5.0.2 on 2024-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_completed_tasks'),
        ('tasks', '0002_task_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, default=None, related_name='completed_tasks', to='tasks.task'),
        ),
    ]
