# Generated by Django 5.0.1 on 2024-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
