# Generated by Django 4.2.10 on 2024-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_profile_pointstoattack'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highest_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
