# Generated by Django 3.2.24 on 2024-03-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_profile_highest_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
