# Generated by Django 4.2.10 on 2024-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_profile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to='badges/'),
        ),
    ]
