# Generated by Django 4.2.10 on 2024-03-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_badge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
    ]
