# Generated by Django 4.2.10 on 2024-03-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_profile_challenges_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monsters_defeated',
            field=models.IntegerField(default=0),
        ),
    ]
