# Generated by Django 4.2.10 on 2024-03-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_profile_monsters_defeated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tree_grown',
            field=models.BooleanField(default=False),
        ),
    ]
